spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8080

app:
  cors:
    allowed-origins: "http://localhost:3000"
