spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none   # IMPORTANT: Flyway manages the schema now

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true   # if tables already exist, mark baseline
    baseline-version: 1
    # clean-disabled is true by default in Boot; keep it safe

server:
  port: 8080

app:
  cors:
    allowed-origins: "http://localhost:3000"
